# Generated by Django 5.2.1 on 2025-08-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_carpet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение превью (публичный URL)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
