# Generated by Django 5.2.1 on 2025-08-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_collection_image_url_alter_collection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Код модели'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет основы'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название ковра'),
        ),
    ]
